// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, account_id, name, description, key, status, created_by, last_used, requests_consumed, product, plan_id, created_at, updated_at
FROM api_keys
WHERE key = $1
`

func (q *Queries) GetAPIKey(ctx context.Context, key uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, key)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.Key,
		&i.Status,
		&i.CreatedBy,
		&i.LastUsed,
		&i.RequestsConsumed,
		&i.Product,
		&i.PlanID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
