// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: plans.sql

package db

import (
	"context"
)

const getPlanByName = `-- name: GetPlanByName :one
SELECT id, account_id, name, rate_limit, burst_size, algorithm, created_at, updated_at
FROM plans
WHERE name = $1
`

func (q *Queries) GetPlanByName(ctx context.Context, name string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByName, name)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.RateLimit,
		&i.BurstSize,
		&i.Algorithm,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
