// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetAPIKey(ctx context.Context, key uuid.UUID) (ApiKey, error)
	GetPlanByName(ctx context.Context, name string) (Plan, error)
}

var _ Querier = (*Queries)(nil)
